### ISSUE TITLE
Delays and update failures

### ISSUE THREAD

**Issue by Lu-vam** [instedd/aida#132] opened 2018-03-14 10:18 UTC
The chatbot often stops working for prolonged periods (usually between 1 and 2 hours) and for no apparent reason. After some time, it restarts working properly, again without any apparent reason. This happens on both the AIDA's aida-stg.instedd.org instance and on our local instance. 

Similarly, it happens that the chatbot does not allow to publish the information for prolonged periods and for no apparent reason (as it successfully publish the same changes after some hours).

**Comment by nditada** [comment] 2018-03-14 18:41
@Lu-vam do you see any error on the screen when the publishing failure happens? Or it publishes successfully but you do not see the changes in Facebook?

**Comment by Lu-vam** [comment] 2018-03-15 08:17
It says 'bot preview failed' when I try to check the preview, and 'bot publishing failed' when I try to publish on Facebook. For example, today it happened when I rescheduled a survey (that I tested on the preview successfully yesterday) - see image. 

![image](https://user-images.githubusercontent.com/36440133/37451327-807f9b4e-2831-11e8-9b13-c8f97f9f9f4a.png)

**Comment by Lu-vam** [comment] 2018-03-16 09:23
Hi @mmuller, it is more than 24 hours that I cannot update / change the information on my chatbot - this is becoming URGENT! Thanks for helping :)

**Comment by nditada** [comment] 2018-03-16 17:22
@Lu-vam we are on it. Please understand that 24 hs is just 8 working hours, we'll update the ticket as soon as we find the cause and fix for the server failure.

**Comment by waj** [comment] 2018-03-16 21:22
It should be working now. I'll close this. In case it happens again please provide an estimate of the date/time when it occurs so we can correlate the issue with the server logs.

**Closed by waj** 2018-03-16 21:22 UTC

**Comment by Lu-vam** [comment] 2018-03-19 09:03
Hi @waj this is happening again now, Monday 19 March - from 9.45am CET / 5.45am GMT-3, on our instance. Is there any way we can fix this ourselves when it happens on our instance?
