### ISSUE TITLE
Clicking Relevance, Bot becomes unusable 

### ISSUE THREAD

**Issue by DigitalHumanitarian** [instedd/aida#176] opened 2018-06-13 21:02 UTC
It is bot 96 that I broke, and the copy I tried to make of it. If I try to go into the bot, I just get a blank screen. Same if I put in the direct URL: https://aida-stg.instedd.org/b/96/behaviour

This is the blank screen:
![aida_and_slack_-_instedd](https://user-images.githubusercontent.com/37674471/41377728-f6aca650-6f2a-11e8-8350-2c46ae0af247.png)

Here is where I clicked and typed and the bot become unusable 
![aida](https://user-images.githubusercontent.com/37674471/41378748-0eb6b634-6f2e-11e8-9f6e-00d4c76252d0.png)

**Comment by nekron** [comment] 2018-07-23 18:21
Duplicate of https://github.com/instedd/aida-ui/issues/152

**Closed by nekron** 2018-07-23 18:21 UTC
