### ISSUE TITLE
Not able to publish bot updates

### ISSUE THREAD

**Issue by Lu-vam** [instedd/aida#252] opened 2018-08-13 09:02 UTC
Hello, I made some changes to my bot and now I am not able to publish anymore!! I see that now the bot shows me where I made mistakes (red dot), but: 
1) I did not change those particular skills and before they were working fine! 
2) I don't understand what is the problem with those skills: for example, in the 'salutation' skill (see pic) I entered all necessary fields... why is it not working?! 

Also note that this problem is also preventing us from using the bot preview.

Thanks, 
Lucia

![error bot](https://user-images.githubusercontent.com/36440133/44022469-fb2238e8-9ee7-11e8-8f65-a3b1003e1722.PNG)

**Comment by nekron** [comment] 2018-08-13 15:16
The main problem is that keywords can't contain spaces. In your example `good morning, good afternoon` should be `good, morning, afternoon`.

Aida never supported keywords with spaces, but never validated them. The bug was manifested in the way that the bot simply wouldn't respond to that keyword. The problem is with the way aida splits the user's message to check for the keywords: we simply take one word at a time and validate against all available keywords. For instance, when the user sends `good morning` we will split `good` and `morning` and check them against a space separated keyword like `good morning` which of course wouldn't match.

We added a validation rule to enforce that keywords don't contain spaces, but apparently we are missing that in the UI error report.

I'm closing this in favor of https://github.com/instedd/aida-ui/issues/209

**Closed by nekron** 2018-08-13 15:16 UTC

**Comment by mmuller** [comment] 2018-08-31 19:28
Working properly in version 50906e3
